/*
    M:N관계 
        1. 현실세계에서 빈번히 나타나지만 주의해야하는 관계이다.
        2.M:N관계를 가진 2개의 테이블은 직접 관계를 맺는 것이 불가능하다.
        3.관계를 맺기 위해서 별도의 테이블이 추가로 필요하다
        4.M:N관계는 1:M 관계 2개로 구현할 수 있다.
*/

DROP TABLE ENROLL_T;
DROP TABLE SUBJECT_T;
DROP TABLE UNIV_STUDENT_T ;


CREATE TABLE UNIV_STUDENT_T
    (
    STU_NO NUMBER  NOT NULL,
    STU_NAME VARCHAR2(32 BYTE)NOT NULL,
    STU_AGE NUMBER  NOT NULL,
    CONSTRAINT PK_UNIV_STU PRIMARY KEY (STU_NO)
    );

CREATE TABLE SUBJECT_T
    (
    SBJ_CODE VARCHAR2(4 BYTE) NOT NULL ,
    SBJ_NAME   VARCHAR2(32 BYTE)NOT NULL UNIQUE,
    교수명   VARCHAR2(32 BYTE)NOT NULL,
    CONSTRAINT PK_SBJ PRIMARY KEY(SBJ_CODE)
   
    );
    
CREATE TABLE ENROLL_T
    (
    EN_NO NUMBER  NOT NULL,
    STU_NO     NUMBER,
    SBJ_CODE VARCHAR2(4 BYTE)  ,
    CONSTRAINT PK_EN PRIMARY KEY(EN_NO),
    CONSTRAINT FK_UNIV_STU_EN FOREIGN KEY(STU_NO) REFERENCES UNIV_STUDENT_T(STU_NO)
    ,CONSTRAINT FK_SBJ_EN FOREIGN KEY(SBJ_CODE) REFERENCES SUBJECT_T(SBJ_CODE)
    );