DROP TABLE SCHEDULE_TBL;
DROP TABLE PLAYER_TBL;
DROP TABLE EVENT_TBL;
DROP TABLE NATION_TBL;


CREATE TABLE NATION_TBL(
    N_CODE NUMBER(3) NOT NULL ,
    N_NAME VARCHAR2(30 BYTE),
    N_PARTI_PERSON NUMBER,
    N_PARTI_EVENT NUMBER,
    N_PREV_RANK NUMBER,
    N_CURR_RANK NUMBER
);

CREATE TABLE EVENT_TBL    
    (
    E_CODE NUMBER,
    E_NAME VARCHAR2(30 BYTE),
    E_FIRST_YEAR NUMBER,
    E_INFO VARCHAR2(100 BYTE)
    );
    
    
    CREATE TABLE PLAYER_TBL
    (
        P_CODE NUMBER(3) NOT NULL,
        P_NAME VARCHAR2(30 BYTE) NOT NULL,
        N_CODE NUMBER(3)NOT NULL,
        E_CODE NUMBER NOT NULL, 
        P_RANK NUMBER,
        P_AGE NUMBER(3)
    );
    
    CREATE TABLE SCHEDULE_TBL
    (
        S_NO NUMBER(3)NOT NULL,
        N_CODE NUMBER(3),
        E_CODE NUMBER,
        S_START_DATE DATE,
        S_END_DATE DATE,
        S_INFO VARCHAR2(100 BYTE)
    );
    
     ALTER TABLE NATION_TBL  ADD  CONSTRAINT PK_NT_TBL PRIMARY KEY(N_CODE);
    ALTER TABLE NATION_TBL MODIFY N_NAME VARCHAR2(30 BYTE) NOT NULL;
    
    ALTER TABLE EVENT_TBL ADD  CONSTRAINT PK_EV_TBL PRIMARY KEY(E_CODE);
    ALTER TABLE EVENT_TBL MODIFY E_CODE  NUMBER NOT NULL;
    ALTER TABLE EVENT_TBL MODIFY E_NAME VARCHAR2(30 BYTE) NOT NULL;
    
    ALTER TABLE PLAYER_TBL ADD CONSTRAINT PK_PL_TBL PRIMARY KEY(P_CODE);
    ALTER TABLE PLAYER_TBL ADD CONSTRAINT FK_PL_TBL_NT FOREIGN KEY (N_CODE) REFERENCES NATION_TBL(N_CODE);
    ALTER TABLE PLAYER_TBL ADD CONSTRAINT FK_PL_TBL_ET FOREIGN KEY (E_CODE) REFERENCES EVENT_TBL(E_CODE);
    ALTER TABLE SCHEDULE_TBL ADD CONSTRAINT FK_SCH_TBL_NT FOREIGN KEY (N_CODE) REFERENCES NATION_TBL(N_CODE);
    ALTER TABLE SCHEDULE_TBL ADD CONSTRAINT FK_SHC_TBL_ET FOREIGN KEY (E_CODE) REFERENCES EVENT_TBL(E_CODE);